import { Construct } from 'constructs';
import { Duration, IResource, Resource } from 'aws-cdk-lib';
import { CfnAssessmentTemplate } from 'aws-cdk-lib/aws-inspector';

/**
 * Interface for an Inspector Assessment Template
 */
export interface IAssessmentTemplate extends IResource {
  /**
   * The Amazon Resource Name (ARN) of the assessment template.
   */
  readonly assessmentTemplateArn: string;
}

/**
 * Properties for creating an Inspector Assessment Template
 */
export interface AssessmentTemplateProps {
  /**
   * The user-defined name that identifies the assessment template that you want to create.
   * @default - no name
   */
  readonly assessmentTemplateName?: string;

  /**
   * The ARN of the assessment target that corresponds to this template.
   */
  readonly assessmentTargetArn: string;

  /**
   * The duration of the assessment run in seconds.
   */
  readonly durationInSeconds: Duration;

  /**
   * The rules packages that are specified for this assessment template.
   */
  readonly rulesPackageArns: string[];

  /**
   * The user-defined attributes that are assigned to every finding that is generated by the assessment run.
   * @default - No user attributes
   */
  readonly userAttributesForFindings?: { [key: string]: string };

}

/**
 * Represents an Inspector Assessment Template
 */
export class AssessmentTemplate extends Resource implements IAssessmentTemplate {
  /**
   * The ARN of the assessment template
   */
  public readonly assessmentTemplateArn: string;

  constructor(scope: Construct, id: string, props: AssessmentTemplateProps) {
    super(scope, id);

    const template = new CfnAssessmentTemplate(this, 'Resource', {
      assessmentTargetArn: props.assessmentTargetArn,
      assessmentTemplateName: props.assessmentTemplateName,
      durationInSeconds: props.durationInSeconds.toSeconds(),
      rulesPackageArns: props.rulesPackageArns,
      userAttributesForFindings: props.userAttributesForFindings ?
        Object.entries(props.userAttributesForFindings).map(([key, value]) => ({ key, value })) : undefined,
    });

    this.assessmentTemplateArn = template.attrArn;
  }
}
