import * as scheduler from '@aws-cdk/aws-scheduler-alpha';
import { ExpectedResult, IntegTest } from '@aws-cdk/integ-tests-alpha';
import { App, Duration, Resource, Stack } from 'aws-cdk-lib';
import { CfnAssessmentTarget, CfnAssessmentTemplate, IAssessmentTemplate } from 'aws-cdk-lib/aws-inspector';
import { InspectorStartAssessmentRun } from '../lib';

export interface AssessmentTemplateProps {
  /**
   * The ARN of the assessment target
   */
  readonly assessmentTargetArn: string;

  /**
   * The duration of the assessment run to start
   */
  readonly durationInSeconds: Duration;

  /**
   * The ARNs of the assessment templates
   */
  readonly assessmentTemplateRulesPackageArns: string[];

  /**
 * The assessment template name
 */
  readonly assessmentTemplateName?: string;

  /**
   * The user-defined attributes assigned to every finding generated by assessment run
   * @default - No user-defined attributes
   */
  readonly userAttributesForFindings?: { [key: string]: string };

}

class MyAssessmentTemplate extends Resource implements IAssessmentTemplate {
  public readonly assessmentTemplateArn: string;

  constructor(scope: Stack, id: string, props: AssessmentTemplateProps) {
    super(scope, id);

    const template = new CfnAssessmentTemplate(this, 'Resource', {
      assessmentTargetArn: props.assessmentTargetArn,
      assessmentTemplateName: props.assessmentTemplateName,
      durationInSeconds: props.durationInSeconds.toSeconds(),
      rulesPackageArns: props.assessmentTemplateRulesPackageArns,
      userAttributesForFindings: props.userAttributesForFindings ?
        Object.entries(props.userAttributesForFindings).map(([key, value]) => ({ key, value })) : undefined,
    });
    this.assessmentTemplateArn = template.attrArn;
  }
}

/*
 * Pre-Stack Verification:
 * Create a managed EC2 instance via console: https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-launch-managed-instance.html
 * and install Amazon Inspector Agent: https://docs.aws.amazon.com/inspector/v1/userguide/inspector_installing-uninstalling-agents.html#install-run-command
 *
 * Stack verification steps:
 * An inspector assessment run by the scheduler
 * The assertion checks whether the assessment run
 */
const app = new App();
const stack = new Stack(app, 'aws-cdk-scheduler-targets-inspector-start-assessment-run');

const assessmentTarget = new CfnAssessmentTarget(stack, 'MyAssessmentTarget');
const assessmentTemplate = new MyAssessmentTemplate(stack, 'MyAssessmentTemplate', {
  assessmentTargetArn: assessmentTarget.attrArn,
  durationInSeconds: Duration.hours(1),
  // https://docs.aws.amazon.com/inspector/v1/userguide/inspector_rules-arns.html#us-east-1
  assessmentTemplateRulesPackageArns: ['arn:aws:inspector:us-east-1:316112463485:rulespackage/0-gEjTy7T7'],
});

new scheduler.Schedule(stack, 'Schedule', {
  schedule: scheduler.ScheduleExpression.rate(Duration.minutes(10)),
  target: new InspectorStartAssessmentRun(assessmentTemplate),
});

const integrationTest = new IntegTest(app, 'integrationtest-inspector-start-assessment-run', {
  testCases: [stack],
  stackUpdateWorkflow: false, // this would cause the schedule to trigger with the old code
});

// Verifies that the assessment run by the scheduler
integrationTest.assertions.awsApiCall('Inspector', 'listAssessmentRuns', {
  AssessmentTemplateArns: [assessmentTemplate.assessmentTemplateArn],
}).assertAtPath(
  'assessmentRunArns.0',
  ExpectedResult.stringLikeRegexp(assessmentTemplate.assessmentTemplateArn),
).waitForAssertions({
  interval: Duration.seconds(30),
  totalTimeout: Duration.minutes(10),
});
